### ISSUE TITLE
Service workery thing

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/YearInfo.github.io#35]

**Comment by HandyHat** [comment]
Need to get the service worker to cache the old page while the fresh content loads - will have to figure out how to tell the service worker to wait for the js.
Also caching is a pain so I might end up using boilerplate - Google has good stuff for this.
Also also this may mean we can update the offline page to show the cached content (with a warning saying the data is out of date)

**Comment by Epacnoss** [comment]
Have fun Aniket!

**Comment by ajhawkings** [comment]
Pog the champs

**Comment by HandyHat** [comment]
OK so the original issue was that the footer was appearing before the js finished rendering - I had a look at the html and since we hadn't set the js to render aynchronously, it should have been loading before the footer. Turns out we had Cloudflare's rocket loader on, which forces all js to load in the background. I turned that off and now the content loads before the footer appears, fixing this issue (and now i don't have to mess with the Service Worker 😉

**Comment by ajhawkings** [comment]
Coooooool
